// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jolzjrpoejbpkcrmqlcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbHpqcnBvZWpicGtjcm1xbGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTI1MDUsImV4cCI6MjA2OTI2ODUwNX0.i-ZsokPPinsiB_nhL0yQENi9BwWtCi0vRpBRPbL_Tck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});